import type { Agent, Match, MatchHistory } from './types'

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'AlphaBot',
    strategy: 'aggressive',
    riskLevel: 'high',
    walletAddress: '0x1234...5678',
    totalWins: 145,
    totalLosses: 32,
    totalMatches: 177,
    totalProfit: 2450.5,
    averageWager: 25,
    currentStreak: 8,
    riskScore: 85,
    winRate: 81.9,
  },
  {
    id: '2',
    name: 'BetaGuard',
    strategy: 'defensive',
    riskLevel: 'low',
    walletAddress: '0x2345...6789',
    totalWins: 128,
    totalLosses: 28,
    totalMatches: 156,
    totalProfit: 1890.25,
    averageWager: 20,
    currentStreak: 5,
    riskScore: 35,
    winRate: 82.05,
  },
  {
    id: '3',
    name: 'GammaFlow',
    strategy: 'balanced',
    riskLevel: 'medium',
    walletAddress: '0x3456...7890',
    totalWins: 112,
    totalLosses: 45,
    totalMatches: 157,
    totalProfit: 1120.75,
    averageWager: 22,
    currentStreak: 3,
    riskScore: 52,
    winRate: 71.34,
  },
  {
    id: '4',
    name: 'DeltaRush',
    strategy: 'aggressive',
    riskLevel: 'high',
    walletAddress: '0x4567...8901',
    totalWins: 98,
    totalLosses: 52,
    totalMatches: 150,
    totalProfit: 890.0,
    averageWager: 18,
    currentStreak: -2,
    riskScore: 78,
    winRate: 65.33,
  },
  {
    id: '5',
    name: 'EpsilonSafe',
    strategy: 'defensive',
    riskLevel: 'low',
    walletAddress: '0x5678...9012',
    totalWins: 105,
    totalLosses: 35,
    totalMatches: 140,
    totalProfit: 1245.5,
    averageWager: 19,
    currentStreak: 4,
    riskScore: 28,
    winRate: 75,
  },
]

export const mockOngoingMatches: Match[] = [
  {
    id: 'match-1',
    agent1: mockAgents[0],
    agent2: mockAgents[2],
    currentRound: 3,
    totalRounds: 5,
    agent1Wins: 2,
    agent2Wins: 0,
    wagerAmount: 50,
    status: 'active',
    timestamp: new Date(),
  },
  {
    id: 'match-2',
    agent1: mockAgents[1],
    agent2: mockAgents[3],
    currentRound: 2,
    totalRounds: 5,
    agent1Wins: 1,
    agent2Wins: 1,
    wagerAmount: 35,
    status: 'active',
    timestamp: new Date(),
  },
]

export const mockMatchHistory: MatchHistory[] = [
  {
    id: 'hist-1',
    opponent: mockAgents[1],
    result: 'win',
    wager: 30,
    score: '3-1',
    profitLoss: 30,
    txHash: '0xabc123...def456',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'hist-2',
    opponent: mockAgents[3],
    result: 'win',
    wager: 25,
    score: '3-0',
    profitLoss: 25,
    txHash: '0xdef456...ghi789',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'hist-3',
    opponent: mockAgents[2],
    result: 'loss',
    wager: 40,
    score: '1-3',
    profitLoss: -40,
    txHash: '0xghi789...jkl012',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'hist-4',
    opponent: mockAgents[4],
    result: 'win',
    wager: 20,
    score: '3-2',
    profitLoss: 20,
    txHash: '0xjkl012...mno345',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
]
